/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MatricularAlunoController;
import Exceptions.UniversidadeException;
import Model.Aluno;
import Model.Curso;
import Model.Turma;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ander
 */
public class MatricularAlunoView extends javax.swing.JFrame {
    
    private final MatricularAlunoController controller;
    /**
     * Creates new form MatricularAlunoView
     */
    public MatricularAlunoView() {
        initComponents();
        iniciarBotoes();
        controller = new MatricularAlunoController(this);
        controller.atualizarCursos();
        controller.atualizarTurmas();
        controller.atualizarAlunos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        cbTurma = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox<>();
        cbAluno = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btMatricular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Curso");

        jLabel3.setText("Turma");

        jLabel5.setText("Aluno");

        btMatricular.setText("Matricular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAluno, 0, 214, Short.MAX_VALUE)
                    .addComponent(cbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTurma, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btMatricular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMatricular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMatricular;
    private javax.swing.JComboBox<Aluno> cbAluno;
    private javax.swing.JComboBox<Curso> cbCurso;
    private javax.swing.JComboBox<Turma> cbTurma;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void iniciarBotoes() {
        btMatricular.addActionListener(e -> {
            try {
                controller.matricularAluno();
            } catch (UniversidadeException ex) {
                exibirMensagem(ex.getMessage());
            }
        });
        
        cbCurso.addItemListener(e -> {
            controller.atualizarTurmas();
        });
    }

    public JComboBox<Aluno> getCbAluno() {
        return cbAluno;
    }

    public JComboBox<Curso> getCbCurso() {
        return cbCurso;
    }

    public JComboBox<Turma> getCbTurma() {
        return cbTurma;
    }   

    private void exibirMensagem(String message) {
        JOptionPane.showMessageDialog(null, message);
    }
}