/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuController;
import Model.DAO.Banco;

/**
 *
 * @author ander
 */
public class MenuView extends javax.swing.JFrame {

    private final MenuController controller;
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        controller = new MenuController();
        initComponents();
        iniciarBotoes();
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadCurso = new javax.swing.JMenuItem();
        miCadTurma = new javax.swing.JMenuItem();
        miCadAluno = new javax.swing.JMenuItem();
        miCadProfessor = new javax.swing.JMenuItem();
        miMatricularAluno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAlunosTurma = new javax.swing.JMenuItem();
        miTurmasAluno = new javax.swing.JMenuItem();
        miAlunosCurso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        miCadCurso.setText("Curso");
        jMenu1.add(miCadCurso);

        miCadTurma.setText("Turma");
        jMenu1.add(miCadTurma);

        miCadAluno.setText("Aluno");
        jMenu1.add(miCadAluno);

        miCadProfessor.setText("Professor");
        jMenu1.add(miCadProfessor);

        miMatricularAluno.setText("Matricular Aluno");
        jMenu1.add(miMatricularAluno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        miAlunosTurma.setText("Alunos x Turma");
        jMenu2.add(miAlunosTurma);

        miTurmasAluno.setText("Turmas x Aluno");
        jMenu2.add(miTurmasAluno);

        miAlunosCurso.setText("Alunos x Curso");
        jMenu2.add(miAlunosCurso);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAlunosCurso;
    private javax.swing.JMenuItem miAlunosTurma;
    private javax.swing.JMenuItem miCadAluno;
    private javax.swing.JMenuItem miCadCurso;
    private javax.swing.JMenuItem miCadProfessor;
    private javax.swing.JMenuItem miCadTurma;
    private javax.swing.JMenuItem miMatricularAluno;
    private javax.swing.JMenuItem miTurmasAluno;
    // End of variables declaration//GEN-END:variables

    private void iniciarBotoes() {
        miCadAluno.addActionListener(e -> {
            controller.navegarCadAluno();
        });
        
        miCadCurso.addActionListener(e -> {
            controller.navegarCadCurso();
        });
        
        miCadProfessor.addActionListener(e -> {
            controller.navegarCadProfessor();
        });
        
        miCadTurma.addActionListener(e -> {
            controller.navegarCadTurma();
        });
        
        miMatricularAluno.addActionListener(e -> {
            controller.navegarMatricularAluno();
        });
        
        miAlunosTurma.addActionListener(e -> {
            controller.navegarReAlunosTurma();
        });
        
        miAlunosCurso.addActionListener(e -> {
            controller.navegarReAlunosCurso();
        });
        
        miTurmasAluno.addActionListener(e -> {
            controller.navegarReTurmasAluno();
        });
    }
}